import React from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { Intro } from '../components/Intro';
import { Profile } from '../components/Profile';
import 'bootstrap/dist/css/bootstrap.css';
const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Intro />
        <Profile />
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  );
};

export default Home;
